
- name : "Debian - Disable required services"
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
    enabled: false
  ignore_errors: true
  with_items:
    - { name: "avahi-daemon" }
    - { name: "cups" }
    - { name: "cups-browsed" }
    - { name: "exim4" }
    - { name: "ssh" }
