# Docker setup

- name: "Docker | Install apt-transport-https"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: "Docker | Add signing key"
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: "Docker | Add repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: "Docker | Installation"
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true

# Add Alias
## Remove all container : docker ps -aq | xargs docker stop | xargs docker rm
- name: "Docker | Add BASH aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.bash_aliases"
    create: yes
    mode: 0644
    line: 'alias {{ item.alias }}="{{ item.commandLine }}"'
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "docker-remove_all", commandLine: "sudo docker system prune -a" }
    - { alias: "docker-remove_all_containers", commandLine: "sudo docker stop \\$(sudo docker ps -a -q); sudo docker rm \\$(sudo docker ps -a -q)" }
    - { alias: "docker-remove_all_images", commandLine: "sudo docker rmi \\$(docker images -a -q)" }
    - { alias: "docker-remove_all_volumes", commandLine: "sudo docker volume rm \\$(sudo docker volume ls -q)" }
    - { alias: "docker-stop_all_containers", commandLine: "sudo docker stop \\$(sudo docker ps -a -q);" }
