- name: Install requirements
  apt:
    name: 
      - cargo
      - feh
      - git-core
      - golang
      - gparted
      - gtk2-engines-murrine 
      - gtk2-engines-pixbuf
      - htop
      - jq
      - keepassxc
      - libjpeg-dev
      - python2
      - python-pip-whl
      - python3
      - python3-pip
      - python3-venv
      - remmina
      - sassc
      - screen
      - terminator
      - tmux
      - vim
      - zulucrypt-gui
    state: present

- name: Create Terminator config directory if it doesn't exist
  file:
    path: "/home/{{ ansible_user }}/.config/terminator/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy Terminator config
  copy:
   src: "./files/terminator_config"
   dest: "/home/{{ ansible_user }}/.config/terminator/config"
   owner: "{{ ansible_user }}"
   group: "{{ ansible_user }}"
   mode: 0644

- name: remove old OpenSSL directory
  file:
    state: absent
    path: /usr/lib/python3/dist-packages/OpenSSL

- name: Install - Python modules
  ansible.builtin.pip:
    name: 
      - colorama
      - psutil
      - lxml
      - netaddr
      - pyopenssl
      - rfc5424-logging-handler
