

- name: "CT-EXPOSER | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/chris408/ct-exposer.git", dest: "{{ OSINT_toolsDir }}/ct-exposer" }

- name: "CT-EXPOSER | Python dependencies installation"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ OSINT_toolsDir }}/ct-exposer; pip3 install -r requirements.txt;
