- type: filestream
  enabled: true
  id: dfir-collection
  take_over: true
  paths:
    - {{ casesDir }}/**/*.json
    - {{ casesDir }}/*.json
  close_inactive: 5m
  fields_under_root: true
  fields:
    type: secubianDFIR
    file.type: json