- type: log
  enabled: true
  paths:
    - {{ casesDir }}/*/*
    - {{ casesDir }}/*
  include_files: [ '\.json$' ]
  close_inactive: 5m
  fields_under_root: true
  fields:
    type: secubianDFIR
    file.type: json

