# Bulk_extractor

- name: "Bulk Extractor | Install requirements"
  apt:
    name: 
      - autoconf 
      - automake
      - flex
      - libewf-dev 
      - openjdk-11-jdk 
    state: present


- name: "Bulk Extractor | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/simsong/bulk_extractor.git", dest: "{{ DFIR_toolsDir }}/bulk_extractor" }

- name: "Bulk Extractor | Setup specific libraries"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: "{{ item.cmdline }}"
  with_items:
    - { cmdline: "cd {{ DFIR_toolsDir }}/bulk_extractor; sudo chmod +x bootstrap.sh; sudo ./bootstrap.sh;" }  
    - { cmdline: "cd {{ DFIR_toolsDir }}/bulk_extractor; sudo ./configure; sudo make; sudo make install;" }  
