
- name: "Loki | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/Neo23x0/Loki.git", dest: "{{ DFIR_toolsDir }}/Loki" }


- name: "Loki | Python modules requirement"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/Loki; pip3 install -r requirements.txt;

- name: "Loki | Threat database update"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/Loki; python3 ./loki-upgrader.py;

- name: "Loki | Add BASH aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.bash_aliases"
    create: yes
    mode: 0644
    line: 'alias loki="cd {{ DFIR_toolsDir }}/Loki; python3 ./loki.py"'
    regexp: "^alias loki="
