- name: "MVT - Mobile Verification Toolkit | Setup"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - mvt
    virtualenv: "$HOME/.pyenv/versions/3.9.18"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv 3.9.18"