

- name: "Timesketch | Create folder"
  become_user: "{{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
  loop:
    - "{{ DFIR_toolsDir }}/timesketch"

- name: "Timesketch | Download setup script"
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh
    dest: "{{ DFIR_toolsDir }}/timesketch/deploy_timesketch.sh"
    mode: 0755 

- name: "Timesketch | Execute deploy script"
  become_user: "{{ user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/timesketch; yes N | sudo ./deploy_timesketch.sh --start-container;

- name: "Timesketch | Create user"
  become_user: "{{ user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/timesketch/timesketch; sudo docker-compose exec timesketch-web tsctl create-user {{ user }} --password {{ user }};

- name: "Timesketch | Add BASH aliases"
  become_user: "{{ user }}"
  lineinfile:
    dest: "~/.bash_aliases"
    create: yes
    mode: 0644
    line: 'alias timesketch="cd {{ DFIR_toolsDir }}/timesketch/timesketch; sudo docker-compose up"'
    regexp: "^alias timesketch="
