# Volatility

- name: "Volatility | Install requirements"
  apt:
    name: 
      - build-essential 
      - capstone-tool 
      - clamav
      - git-core
      - libcapstone-dev
      - libraw1394-11 
      - libssl-dev
      - tzdata
      - yara 
    state: present

- name: "Volatility | Install python libraries needed by volatility"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - construct
      - distorm3
      - future
      - openpyxl
      - pdbparse
      - pefile
      - pillow
      - pycrypto
      - pycryptodome
      - pytz
      - setuptools
      - ujson
    virtualenv: "$HOME/.pyenv/versions/2.7.18"
    virtualenv_command: $HOME/.pyenv/bin/pyenv virtualenv 2.7.18

- name: "Volatility | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { repo: "https://github.com/volatilityfoundation/volatility.git", dest: "{{ DFIR_toolsDir }}/data_processing/volatility" }

#- name: "Volatility | Create YARA Symbolic Link for library"
#  ansible.builtin.file:
#    dest: "/usr/lib/libyara.so"
#    src: "/usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so"
#    state: link


# Volatility Plugins 
## most of https://github.com/sans-dfir/sift-files/tree/master/volatility should be here
## src : https://github.com/juju4/ansible-volatility/blob/master/tasks/volatility-modules.yml

- name: "Volatility | Ensure volatility plugins directory exists"
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins"
    mode: '0755'
    state: directory

- name: "Volatility | Set up plugins developed and maintained by the community"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/volatilityfoundation/community.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/community"
    force: yes

## http://blog.jpcert.or.jp/2016/12/a-new-tool-to-d-d6bc.html
## https://blog.jpcert.or.jp/2018/08/volatility-plugin-for-detecting-cobalt-strike-beacon.html
- name: Artifact Analysis tool from JP-CERT
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/JPCERTCC/aa-tools.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/aa-tools"
    force: yes

- name: Autoruns
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/tomchop/volatility-autoruns
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/volatility-autoruns"
    force: yes

- name: Bitlocker keys retrieving
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/elceef/bitlocker
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/elceef-bitlocker"
    force: yes

- name: Malware config extractor - plugx, andromeda
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/arbor-jjones/volatility_plugins.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/plugx+andromeda"
    force: yes

- name: "Bash | Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.bash_aliases"
    create: yes
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.commandLine }}'"
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "vol.py", commandLine: "$HOME/.pyenv/versions/2.7.18/bin/python {{ DFIR_toolsDir }}/data_processing/volatility/vol.py" }
