

- name: "Zircolite | Download repository"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
  with_items:
    - { repo: "https://github.com/wagga40/Zircolite.git", dest: "{{ DFIR_toolsDir }}/Zircolite" }

- name: "Zircolite | Requirements tools installation"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/Zircolite; pip3 install -r requirements.txt 

- name: "Zircolite | Bash - Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.bash_aliases"
    create: yes
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.commandLine }}'"
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "zircolite.py", commandLine: "python3 {{ DFIR_toolsDir }}/Zircolite/zircolite.py" }
