

- name: "DidierStevensSuite | Download repository"
  become_user: "{{ user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
    force: true
  with_items:
    - { repo: "https://github.com/DidierStevens/DidierStevensSuite.git", dest: "{{ DFIR_toolsDir }}/DidierStevensSuite" }


- name: "DidierStevensSuite | set executable"
  ansible.builtin.shell: chmod +x {{ DFIR_toolsDir }}/DidierStevensSuite/*.py


- name: "DidierStevensSuite | Bash - Add aliases"
  become_user: "{{ user }}"
  lineinfile:
    dest: "~/.bashrc"
    create: yes
    mode: 0644
    line: "export PATH=$PATH:{{ DFIR_toolsDir }}/DidierStevensSuite"
    regexp: "^export PATH=$PATH:{{ DFIR_toolsDir }}/DidierStevensSuite"
